overrides:
  'exceljs>archiver': 8.0.0
  'exceljs>unzipper': 0.12.5
  'exceljs>uuid': 11.1.1
  postcss: 8.5.18
  sharp: 0.35.0

strictDepBuilds: false

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

allowBuilds:
  sharp: set this to true or false
  unrs-resolver: set this to true or false
