overrides:
  'exceljs>archiver': 7.0.1
  'exceljs>unzipper': 0.12.5
  'exceljs>uuid': 11.1.1
  'readdir-glob>minimatch': 9.0.9
  'minimatch@9.0.9>brace-expansion': 5.0.8
  postcss: 8.5.18
  sharp: 0.35.0

patchedDependencies:
  archiver-utils@5.0.2: patches/archiver-utils@5.0.2.patch

strictDepBuilds: false

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

allowBuilds:
  sharp: set this to true or false
  unrs-resolver: set this to true or false
