overrides:
  postcss: 8.5.15

strictDepBuilds: false

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

allowBuilds:
  sharp: set this to true or false
  unrs-resolver: set this to true or false
